### ISSUE TITLE
Possibility to expand TitleManager support to BossBar?

### ISSUE THREAD

**Issue by mibby** [Puharesource/TitleManager#118]
Would it be possible to expand TitleManager features to support broadcasting a BossBar for a duration? Example use would be to broadcast a message for x duration such as a global notice if someone donated or keep it up permanently with a message if running an event, to then disable it when the event is over. Utilizing colored message as well as the various BossBar bar styles / health drain for remaining duration, with a command to force remove all bars in the event you'd like to stop the message?

As well as if a previous bossbar already has a task scheduled to run for say 10 minutes, force that bossbar to display on players who login for the first time after it had already been initiated so it would reappear when relogging?

**Comment by Puharesource** [comment]
I have been thinking of expanding to the BossBar, we'll see if I get around to adding that though as I'd have to add support for previous versions, which would require me to spawn actual bosses for a few versions.

**Comment by mibby** [comment]
Bump. ^^

**Comment by CDAGaming** [comment]
Bump. ^^
Would like to see this in the Future :P

**Comment by Puharesource** [comment]
Still on my todo list, but I still don't know when I'll release this as I'd love to have backward compatibility with older versions, that only worked when there was an Ender Dragon or Wither in the world, though we'll see I might just go with a lazy route.

**Comment by mibby** [comment]
@Puharesource Any progress? I'm eager to get rid of the plugin UltraBars so I can have everything inclusive in TitleManager. :)

**Comment by mibby** [comment]
@Puharesource Bumpity bump. Any progress on possibly having a form of boss bar announcements? Similar to UltraBar plugin but contained all within TitleManager.

**Comment by mibby** [comment]
Here is the UltraBar plugin config for reference.

```
# 
#                        UltraBar                          #
bstats: false
update_checker: false
WorldGuardRegion:
  Enabled: false
  Message: '&6<< &b%region% &6>>'
  Message2: '&b%region% &3<<>> &6and &c%number%&6 more.'
OnJoin:
  BossBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
    Color: green
    Time: 10
    Style: '6'
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
OnDeath:
  BossBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
    Color: green
    Time: 10
    Style: '6'
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
OnCommand:
  list:
  - examplecmd
  examplecmd:
    BossBar:
      Message: '&6You ran a command!'
      Color: green
      Time: 10
      Style: '6'
      Health: 1
    ActionBar:
      Message: '&6ActionBars can be used&6!'
    Title:
      Message: '&6Along with titles.&6'
      SubTitle: '&bThese support placeholderapi!'
      fadein: 5
      fadeout: 5
      time: 20
BossBarMessages:
  Enabled: false
  World_Whitelist_Enabled: false
  Random_Order: false
  World_Whitelist:
  - world
  Number_Of_Messages: 3
  '1':
    Message: '&1BossBar #1'
    Color: green
    Style: '6'
    Time: 10
  '2':
    Message: '&2BossBar #2'
    Color: blue
    Style: '6'
    Time: 10
  '3':
    Message: '&3BossBar #3'
    Color: red
    Style: '6'
    Time: 10
Title_Announcements:
  Enabled: false
  Random_Order: false
  Number_Of_Messages: 3
  Time: 20
  '1':
    Message: '&6Message 1&6'
    SubTitle: '&bMeassage 1'
    fadein: 5
    fadeout: 5
    time: 20
  '2':
    Message: '&6Message 2&6'
    SubTitle: '&bMessage 2'
    fadein: 5
    fadeout: 5
    time: 20
  '3':
    Message: '&6Message 3&6'
    SubTitle: '&bMessage 3'
    fadein: 5
    fadeout: 5
    time: 20
Action_Announcements:
  Enabled: false
  Random_Order: false
  Number_Of_Messages: 3
  Time: 10
  '1':
    Message: Message 1
  '2':
    Message: Message 2
  '3':
    Message: Message 3
```

Allows setting up scheduled boss bar announcements in-game, as well as running one-off messages via a command to everyone online. i.e. ```bar sendall &f&lServer_restart_in:_&b&l1_minute blue 1 60```

https://github.com/ryandw11/UltraBar/wiki/Configuration
