### ISSUE TITLE
Probleme with animations

### ISSUE THREAD

**Issue by Evandre** [Puharesource/TitleManager#26]
When you have only the animation :1 in the footer/header , it works . But when you add a line or write something , even a single letter , the animation doesnt work anymore , it shows only the name animation:test1.
Here the pic : http://imgur.com/Z1KMQEF
.
Thank you
-Evandre , owner of OsteriaCraft

**Comment by Puharesource** [comment]
You need to add that to the animation itself.

Currently (this will be fixed in the future) the plugin doesn't support for multiple animations at once.
So what you need to do is add all of your extra stuff, straight to the animation.

So let's say you've got an animation called a1 and you want your other stuff to be added as well, you'll have to do what we're going to do to a2.
````
a1:
  frames:
  - '_--'
  - '-_-'
  - '--_'

a2:
  frames:
  - '_--\nTon Ping: {PING}\nTon compte: {MONEY}\n/help * /infos * /staff'
  - '-_-\nTon Ping: {PING}\nTon compte: {MONEY}\n/help * /infos * /staff'
  - '--_\nTon Ping: {PING}\nTon compte: {MONEY}\n/help * /infos * /staff'
````

Sorry for the inconvenience, but for the time being, you will have to do it that way.
